print("Hello")
print("python is installed")
print('Eli doesn\'t have data right now, so she is back here')
print('she said "Don\'t do that"')
print("My name is " + "Elizabeth")
print("This costs " + str(60) + " Naira")
print("This costs " + str(60 + 20) + " Naira")
print("This costs " + "60 + 20" + " Naira")
print("Hello, " + "Jade")
print("H" + "e" + "l" + "l" + "o")
print("Hello:Nick")
print(("Hello:Nick").split(":"))
print("My name is " + "Hello:Nick:World".split(":")[1])
print("My other name is " + "Hello:Nick:World:William".split(":")[3])
print(["Movies, Games, Python"][0])
print(["Movies, Games, Python"])
print(["Movies", "Games", "Python"][0])
print(["Movies", "Games", "Python", "Books"][3])
print("I Like Python and " + ["Movies", "Python", "Games"][0])